Making fuel for the LAMBCHOP's reactor core is a tricky process because of the exotic matter involved. It starts as raw ore, then during processing, begins randomly changing between forms, eventually reaching a stable form. There may be multiple stable forms that a sample could ultimately reach, not all of which are useful as fuel. 

Commander Lambda has tasked you to help the scientists increase fuel creation efficiency by predicting the end state of a given ore sample. You have carefully studied the different structures that the ore can take and which transitions it undergoes. It appears that, while random, the probability of each structure transforming is fixed. That is, each time the ore is in 1 state, it has the same probabilities of entering the next state (which might be the same state).  You have recorded the observed transitions in a matrix. The others in the lab have hypothesized more exotic forms that the ore can become, but you haven't seen all of them.

Write a function solution(m) that takes an array of array of nonnegative ints representing how many times that state has gone to the next state and return an array of ints for each terminal state giving the exact probabilities of each terminal state, represented as the numerator for each state, then the denominator for all of them at the end and in simplest form. The matrix is at most 10 by 10. It is guaranteed that no matter which state the ore is in, there is a path from that state to a terminal state. That is, the processing will always eventually end in a stable state. The ore starts in state 0. The denominator will fit within a signed 32-bit integer during the calculation, as long as the fraction is simplified regularly. 



For example, consider the matrix m:

[
  
`  [0,1,0,0,0,1] `,  # s0, the initial state, goes to s1 and s5 with equal probability

 ` [4,0,0,3,2,0] `,  # s1 can become s0, s3, or s4, but with different 
  probabilities
  
 ` [0,0,0,0,0,0]`,  # s2 is terminal, and unreachable (never observed in practice)

 ` [0,0,0,0,0,0]`,  # s3 is terminal

 ` [0,0,0,0,0,0]`,  # s4 is terminal

 ` [0,0,0,0,0,0]`,  # s5 is terminal

]


So, we can consider different paths to terminal states, such as:


s0 -> s1 -> s3

s0 -> s1 -> s0 -> s1 -> s0 -> s1 -> s4

s0 -> s1 -> s0 -> s5

Tracing the probabilities of each, we find that

s2 has probability 0

s3 has probability 3/14

s4 has probability 1/7

s5 has probability 9/14

So, putting that together, and making a common denominator, gives an answer in the form of
[s2.numerator, s3.numerator, s4.numerator, s5.numerator, denominator] which is

` [0, 3, 2, 9, 14]. `

Languages
=========

To provide a Java solution, edit Solution.java
To provide a Python solution, edit solution.py

Test cases
==========
Your code should pass the following test cases.
Note that it may also be run against hidden test cases not shown here.

---

-- Java cases --

---
- Input:

` Solution.solution(  {{0, 2, 1, 0, 0}, {0, 0, 0, 3, 4}, {0, 0, 0, 0, 0}, {0, 0, 0, 0,0}, {0, 0, 0, 0, 0}}          ) `



- Output:
`    [7, 6, 8, 21] `


- Input: 
` Solution.solution({{0, 1, 0, 0, 0, 1}, {4, 0, 0, 3, 2, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}}) `

- Output:
` [0, 3, 2, 9, 14] `

---

-- Python cases --

---

- Input:
` solution.solution([[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]]) `

- Output: 
`    [7, 6, 8, 21] `

- Input:
`
solution.solution([[0, 1, 0, 0, 0, 1], [4, 0, 0, 3, 2, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]) `

- Output:
  `  [0, 3, 2, 9, 14] `


[
  
`  [0,1,0,0,0,1] `,  # s0, the initial state, goes to s1 and s5 with equal probability

 ` [4,0,0,3,2,0] `,  # s1 can become s0, s3, or s4, but with different 
  probabilities
  
 ` [0,0,0,0,0,0]`,  # s2 is terminal, and unreachable (never observed in practice)

 ` [0,0,0,0,0,0]`,  # s3 is terminal

 ` [0,0,0,0,0,0]`,  # s4 is terminal

 ` [0,0,0,0,0,0]`,  # s5 is terminal

]

s2 has probability 0

s3 has probability 3/14

s4 has probability 1/7

s5 has probability 9/14

Constraints 

---

#### Python
======

Your code will run inside a Python 2.7.13 sandbox. All tests will be run by calling the solution() function.

Standard libraries are supported except for bz2, crypt, fcntl, mmap, pwd, pyexpat, select, signal, termios, thread, time, unicodedata, zipimport, zlib.

Input/output operations are not allowed.

Your solution must be under 32000 characters in length including new lines and and other non-printing characters.

### The matrix for the below example:

` m=[[1,2,2,0,0,3], `

` [2,0,0,3,5,0], `

` [0,0,2,0,7,0], `

` [0,0,0,0,0,0], `

` [0,0,0,0,0,0]] `

In [92]:
# 1. Index the terminals of any given square matrix
# 2. Find 'root paths'
    # Which arrays contain the terminal state?
# 3. Add generalized conditions
# 4. Treat double (or alternative) cases/paths
# 5. Treat 'cyclic' paths
from fractions import Fraction
from copy import deepcopy
import numpy as np

m=np.array([
[2,1,3,3,0,1],
[4,2,4,3,2,0],
[3,1,3,1,1,0],
[4,1,1,5,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])


m=[
[0,1,0,1,0,0],
[4,0,0,3,2,0],
[3,1,3,1,1,0],
[4,1,1,5,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]
m=[[0,1,0,0,0,1],
   [4,0,0,3,2,0],
   [0,0,0,0,0,0],
   [0,0,0,0,0,0],
   [0,0,0,0,0,0],
   [0,0,0,0,0,0]]


m=([[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]])



m= [
            [1, 1, 0, 1],
            [1, 1, 0, 0],
            [0, 0, 0, 0],
            [0, 0, 0, 0]
        ]
# m = [
#             [0, 0, 0, 0],
#             [1, 1, 1, 1],
#             [1, 1, 1, 1],
#             [1, 1, 1, 1]
#         ]


m=np.array(m)
m0=deepcopy(m)


diag=deepcopy(m).diagonal()
np.fill_diagonal(m, 0)

# Index terminals:
term=np.where(np.sum(m, axis=1)==0)[0]
# P=0 terminals:
p0term=np.where(np.sum(m, axis=0)==0)[0]

print("m",m)

nonterm=np.setdiff1d(list(range(len(m))),term)


# Remove P=0 terminals from term list
indp0=np.where(term==p0term)
term=np.delete(term,indp0)    


# prepare dict
dm2=dict()
for t in term:
  #print(t,':\t',np.count_nonzero(np.nonzero(m)[1] == t))
 # dm[t]=np.count_nonzero(np.nonzero(m)[1] == t)
  for rowi in range(len(m)):
    if m[rowi][t] >0:
      dm2.setdefault(t, []).append(rowi)
      #dm2[t].append(rowi)




dtrm=dict()
for trm in term:
  trmd=np.nonzero(m[:,trm])[0]
  if len(trmd)>1:
    
    dtrm[trm]=deepcopy(m)[:,trm]
    m[:,trm]=0

M=[]
if len(dtrm)>0:
  for k in dtrm.keys():
    for i in range(len(dtrm[k])):
      if dtrm[k][i]>0:
        mc=deepcopy(m)

        #print("mcki:",mc[k,i])

        val=deepcopy(dtrm[k][i])
        mc[:,k][i]=val

        M.append(mc)



for k in dm2.keys():
  if len(dm2[k])>1:
    for v in dm2[k]:
      mx=deepcopy(m)
      #print(mx[v][k])
      mx[v][k]=0

      M.append(mx)
if len(M)<2:
  M=[m]



def hasInd(m_,nonterm, state):
  for i in nonterm:
    
    if state in np.nonzero(m_[i])[0]:
      

      return i
  return -1



lstx2=[]
for m_ in M:

  #print(m)
  for t in term:
    #for v in dm2[t]:
      lstx=[]
      while t>0:
        lstx.append(t)
        t=hasInd(m_,nonterm,t)
        if t==0:
          lstx.append(t)
          break
      lstx2.append(lstx)
#print('lstx2:::::::::',len(lstx2))

if len(lstx2)>1:
    roots=np.unique(lstx2)
    rootss=deepcopy(roots)
    roots=[]

    for root in rootss:
      if 0 in root:
        roots.append(root)

else:
    roots=lstx2

sets=[]
cycles=[]
for i in range(m.shape[0]):
  for j in range(m.shape[1]):

#   print(i)
   #if i != j:
   if set((i,j)) not in sets:
      sets.append(set((i,j))) 

      if m[i][j] != 0 and m[j][i] != 0:# and i!=j:
#        print('CYCLE:')
        cycles.append((i,j))

for i in range(len(diag)):
  if diag[i]>0:
    cycles.append((i,i))

np.fill_diagonal(m,diag)
print('roots: {}, cycles: {}'.format(roots, cycles))



m [[0 1 0 1]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
roots: [[3, 0]], cycles: [(0, 1), (0, 0), (1, 1)]


In [91]:
# m=np.array([
            
# [0,1,0,1,0,1],
# [4,0,0,3,2,0],
# [3,1,0,1,1,0],
# [4,1,1,0,1,4],
# [0,0,0,0,0,0],
# [0,0,0,0,0,0]

# ])
m=m0
mprob=[m[i]/np.sum(m,axis=1)[i] for i in nonterm]

# Get root probs

roots[0]
rootprobdict=dict()

for root in roots:
    rootprobdict[root[0]]=[]

probs=[]
for root in roots:
  prob=[]
  #print("Path: ")
  for i in range(len(root)-1):
    #print("[{},{}] ".format(root[i+1],root[i]) )
    prob.append(mprob[root[i+1]][root[i]])
    
    #print(mprob[root[i+1]][root[i]])
  print()
  probs.append(prob)
  rootprobdict[root[0]].append(prob)


IndexError: list index out of range

In [73]:
print("probs: ",probs)
print("roots: ",roots)
print("cycles: ",cycles)

rootprobdict
#sumRepProb(mprob[0][0]*mprob[0][1])



probs:  [[0.3333333333333333]]
roots:  [[3, 0]]
cycles:  [(0, 1), (0, 0), (1, 1)]


{3: [[0.3333333333333333]]}

In [74]:
# add 'zero' cycles
def addzerocycles(root,cycles):
    for c in cycles:
        if root[-2] in c and 0 in c:
            return c
    

In [75]:
def getCyclePath1(root, nonterm, cycles):
  cs=[]
  q=[]
  for r in root:
    if r in nonterm:# and r!=0:
      for c in cycles:
        if r in c:# and 0 not in c:
          cs.append(c)
          if r==c[0]:# and c[1]!=0:
            q.append(c[1])
          else:#if c[0]!=0:
            q.append(c[0])

  if 0 in q:
    q.remove(0)
  return q,cs


In [76]:
def getCyclePath2(q,cs,cycles,root):
  
  qpl=[]
  while len(q)>0:
    # print('lenq:',len(q))
    qp=q.pop()
    # print('qp:',qp)
    for c in cycles:
      
      if qp in c:# and 0 not in c:
        cs.append(c)
        if qp==c[0]   and c[1] not in qpl: #and c[1]!=0:
          q.append(c[1])
        elif c[0] not in qpl:# and c[0]!=0  :
          q.append(c[0])
        qpl.append(qp)
  cs=set(cs)
#   c=addzerocycles(root,cycles)
#   if c:
#     cs.add(c)
        
  return cs

In [77]:
cycles
#roots


[(0, 1), (0, 0), (1, 1)]

In [78]:
# i=1

# gcp1=getCyclePath1(roots[i], nonterm, cycles)
# # print(gcp1)
# # print(deepcopy(gcp1[0]))
# cpath=getCyclePath2(gcp1[0],gcp1[1],cycles,roots[i])

# cpath



In [79]:
# cpath
# mprob[1][3]
# mprob[3][1]

# cps=[]
# for cp in cpath:
#     print(cp)
#     if cp[0]!=cp[1]:
#         cps.append(mprob[cp[0]][cp[1]]*mprob[cp[1]][cp[0]])
#     elif cp[0]==cp[1]:
#         cps.append(mprob[cp[0]][cp[1]])
# cps

# dict for roots

In [80]:
# dict for roots
rootdict=dict()
for root in roots:
    rootdict[root[0]]=[]
for root in roots:
    rootdict[root[0]].append(root)
rootdict



{3: [[3, 0]]}

# dict for probs for roots


In [81]:
# dict for probs for roots
# see above
rootprobdict
    

{3: [[0.3333333333333333]]}

# dict for cycles per root


In [82]:
# dict for cycles per root
cycrootdict=dict()
for root in roots:
        cycrootdict[root[0]]=[]
for root in roots:

    gcp1=getCyclePath1(root, nonterm, cycles)
    # print(gcp1)
    # print(deepcopy(gcp1[0]))
    cpath=getCyclePath2(gcp1[0],gcp1[1],cycles,root)
    cycrootdict[root[0]].append(cpath)



# dict for prob of cycles per root

In [83]:
# dict for prob of cycles per root
# ### As above #####################
# cps=[]
# for cp in cpath:
    
#     if cp[0]!=cp[1]:
#         cps.append(mprob[cp[0]][cp[1]]*mprob[cp[1]][cp[0]])
#     elif cp[0]==cp[1]:
#         cps.append(mprob[cp[0]][cp[1]])
# ##################################



### Not as above #################

def getcycprob(cpath,mprob):
    cps=[]
    
    for cp in cpath:
        #print(cp)
        if cp[0]!=cp[1]:
            cps.append( mprob[cp[0]][cp[1]]*mprob[cp[1]][cp[0]])
        elif cp[0]==cp[1]:
            cps.append( mprob[cp[0]][cp[1]])
    return cps
##################################


cycrootprobdict=dict()
for root in roots:
    cycrootprobdict[root[0]]=[]
for k in cycrootdict.keys():
    for v in cycrootdict[k]:
        
        cycrootprobdict[k].append(getcycprob(v,mprob))
                                
                                
        

cycrootprobdict

{3: [[0.16666666666666666, 0.3333333333333333, 0.5]]}

In [84]:
print("dict for roots:\n",rootdict)
print("dict for probs for roots:\n",rootprobdict)
print()
print("dict for cycles per root:\n",cycrootdict)
print()
print("dict for prob of cycles per root:\n",cycrootprobdict)


dict for roots:
 {3: [[3, 0]]}
dict for probs for roots:
 {3: [[0.3333333333333333]]}

dict for cycles per root:
 {3: [{(0, 1), (0, 0), (1, 1)}]}

dict for prob of cycles per root:
 {3: [[0.16666666666666666, 0.3333333333333333, 0.5]]}


In [85]:
def sumRepProb(A):
  return (A**(1e5+1)-1)/(A-1)
def getFractions(rootprobdict,cycrootprobdict,roots):

    prod3=0
    # dictionary for final fractions
    fracdict=dict()
    for root in roots:
        fracdict[root[0]]=[]
     
    
    
    for k in rootprobdict:
        for lst in rootprobdict[k]:
            prod2=[]
            prod1=np.prod(lst)
            for v in cycrootprobdict[k]:
                if len(v)>0:
                    #print("v",v)
                    prod2.append([sumRepProb(e) for e in v])
            #print("pr2",prod2)
            prod3=np.prod(prod2)
            fracdict[k].append(prod1*prod3)
    return fracdict  
    
    
    
    
    
fracdict=getFractions(rootprobdict,cycrootprobdict,roots)    
fracdict

{3: [1.1999999999999997]}

# add up (sum) similar terminals

In [86]:
# add similar terminals

for k in fracdict:
    fracdict[k]=np.sum(fracdict[k])
fracdict
for k in fracdict:
    z=fracdict[k]
    fracdict[k]=Fraction(*z.as_integer_ratio()).limit_denominator()
fracdict

{3: Fraction(6, 5)}

---

# get lowest common denominator

In [87]:
# get lowest common denominator
def returnInt(fraction):
    return (int(str(fraction).split('/')[0]),int(str(fraction).split('/')[1]))

intfracdict=dict()
for k in fracdict.keys():
    #print(returnInt(fracdict[k]))
    intfracdict[k]=returnInt(fracdict[k])


intfracdict

denominators=dict()
nominators=dict()
for k in intfracdict.keys():
    denominators[k]=intfracdict[k][1]
    nominators[k]=intfracdict[k][0]
#     if type(intfracdict[k]) is 'tuple':
#         print("type:")
  
# get 'orphan' states
orphanterm=[]
for c in range(m0.shape[1]):
    if sum(m0[:,c])==0 and sum(m0[c,:])==0:
        orphanterm.append(c)
term2=list(set(list(term)+ orphanterm    ))
#term=term+orphanterm
for t in term2:
    #print(t)
    if t not in intfracdict.keys():
        intfracdict[t]=0
print(denominators)
print(nominators)
term2
intfracdict
term

{3: 5}
{3: 6}


array([3], dtype=int64)

In [88]:
import math

def lcm(a, b):
    return abs(a*b) // math.gcd(a, b)

nominatorsL=list(nominators.values())
denominatorsL=list(denominators.values())

def getLcm(denominators):
 
    lcm = denominators[0]
    for i in denominators[1:]:
      lcm = lcm*i//math.gcd(lcm, i)
    return(lcm)

# 3/14; 1/7; 9/14
#l=denominators#[14,7,14]
# for n in range(len(l)-1):
#   print(lcm(l[n-1],l[n]))
c=getLcm(denominatorsL)
print(denominatorsL)
print(c)
nommul=[]
for i in range(len(denominatorsL)):
    
    nominatorsL[i]*=(int(c/denominatorsL[i]))
    #nominators[term2[i]]=nominatorsL[i]

nk=list(nominators.keys())
nominatorsdict2=dict()
for i in range(len(nk)):
    nominatorsdict2[nk[i]]=nominatorsL[i]
    
nominatorsdict2 

(947581*938065)/165659507

getLcm([938065, 947581])

[5]
5


888892570765

In [1]:

LCM=getLcm(list(denominators.values()))


result=[]
for t in term2:
    if t in nominatorsdict2.keys():
        result.append(nominatorsdict2[t])
    else:
        result.append(0)
        
result.append(LCM)
result

NameError: name 'getLcm' is not defined

In [54]:

def sumRepProb(A):
  return (A**(50+1)-1)/(A-1)
# #S0 --> S2 --> S4

# z=sumRepProb(mp[0][0])*sumRepProb(mp[1][0]*mp[0][1])*mp[0][2]*sumRepProb(mp[2][2])*mp[2][4]
# z=sumRepProb(mp[0][0])*sumRepProb(mp[1][0]*mp[0][1])*mp[0][1]*mp[1][3]

# Fraction(*z.as_integer_ratio()).limit_denominator()


In [55]:
# test

def sumRepProb(A):
  return (A**(50+1)-1)/(A-1)

z=sumRepProb(0.2222222222222222)*0.5
#z=0.5714285714285714*0.6666666666666666
z=0.2857142857142857
Fraction(*z.as_integer_ratio()).limit_denominator()


Fraction(2, 7)

In [56]:
orphanterm=[]
for c in range(m0.shape[1]):
    if sum(m0[:,c])==0 and c not in nonterm:
        orphanterm.append(c)

In [57]:
orphanterm

[]

In [24]:
def getLcm(denominators):
 
    lcm = denominators[0]
    for i in denominators[1:]:
      lcm = lcm*i//math.gcd(lcm, i)
    return(lcm)

In [25]:
dm2

{4: [1, 2, 3]}

In [34]:
list(set(list(term)+ list(p0term)    ))

[4, 5]

In [58]:
term2

[2, 3, 4]