Making fuel for the LAMBCHOP's reactor core is a tricky process because of the exotic matter involved. It starts as raw ore, then during processing, begins randomly changing between forms, eventually reaching a stable form. There may be multiple stable forms that a sample could ultimately reach, not all of which are useful as fuel. 

Commander Lambda has tasked you to help the scientists increase fuel creation efficiency by predicting the end state of a given ore sample. You have carefully studied the different structures that the ore can take and which transitions it undergoes. It appears that, while random, the probability of each structure transforming is fixed. That is, each time the ore is in 1 state, it has the same probabilities of entering the next state (which might be the same state).  You have recorded the observed transitions in a matrix. The others in the lab have hypothesized more exotic forms that the ore can become, but you haven't seen all of them.

Write a function solution(m) that takes an array of array of nonnegative ints representing how many times that state has gone to the next state and return an array of ints for each terminal state giving the exact probabilities of each terminal state, represented as the numerator for each state, then the denominator for all of them at the end and in simplest form. The matrix is at most 10 by 10. It is guaranteed that no matter which state the ore is in, there is a path from that state to a terminal state. That is, the processing will always eventually end in a stable state. The ore starts in state 0. The denominator will fit within a signed 32-bit integer during the calculation, as long as the fraction is simplified regularly. 



For example, consider the matrix m:

[
  
`  [0,1,0,0,0,1] `,  # s0, the initial state, goes to s1 and s5 with equal probability

 ` [4,0,0,3,2,0] `,  # s1 can become s0, s3, or s4, but with different 
  probabilities
  
 ` [0,0,0,0,0,0]`,  # s2 is terminal, and unreachable (never observed in practice)

 ` [0,0,0,0,0,0]`,  # s3 is terminal

 ` [0,0,0,0,0,0]`,  # s4 is terminal

 ` [0,0,0,0,0,0]`,  # s5 is terminal

]


So, we can consider different paths to terminal states, such as:


s0 -> s1 -> s3

s0 -> s1 -> s0 -> s1 -> s0 -> s1 -> s4

s0 -> s1 -> s0 -> s5

Tracing the probabilities of each, we find that

s2 has probability 0

s3 has probability 3/14

s4 has probability 1/7

s5 has probability 9/14

So, putting that together, and making a common denominator, gives an answer in the form of
[s2.numerator, s3.numerator, s4.numerator, s5.numerator, denominator] which is

` [0, 3, 2, 9, 14]. `

Languages
=========

To provide a Java solution, edit Solution.java
To provide a Python solution, edit solution.py

Test cases
==========
Your code should pass the following test cases.
Note that it may also be run against hidden test cases not shown here.

---

-- Java cases --

---
- Input:

` Solution.solution(  {{0, 2, 1, 0, 0}, {0, 0, 0, 3, 4}, {0, 0, 0, 0, 0}, {0, 0, 0, 0,0}, {0, 0, 0, 0, 0}}          ) `



- Output:
`    [7, 6, 8, 21] `


- Input: 
` Solution.solution({{0, 1, 0, 0, 0, 1}, {4, 0, 0, 3, 2, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}}) `

- Output:
` [0, 3, 2, 9, 14] `

---

-- Python cases --

---

- Input:
` solution.solution([[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]]) `

- Output: 
`    [7, 6, 8, 21] `

- Input:
`
solution.solution([[0, 1, 0, 0, 0, 1], [4, 0, 0, 3, 2, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]) `

- Output:
  `  [0, 3, 2, 9, 14] `


In [ ]:
import numpy as np
from fractions import Fraction

In [ ]:

cnt=0
n=1e5
for i in range(int(n)):
  if np.random.choice([0,3, 4],1, p=[4/9, 3/9, 2/9])[0]==0:
    cnt+=1
cnt/int(n)



4/9*0.5*2/9+0.5*2/9


# #Fraction(0.4*0.5*2/9+0.5*0.2).limit_denominator()

# #1/7



0.16049382716049382

In [ ]:
4/9*0.5*2/9+0.5*2/9
#1.5*(4/9*2/9)

0.16049382716049382

In [ ]:
def solution(m):
    # Your code here
    # In: array of arrays (>=0 ints): how many times the state has changed
    # to the next
    # Out: 
    [ [, , , ], 
      [, , , ],
      [, , , ],
      [, , , ],
      [, , , ]
          

    ]
    

SyntaxError: ignored

In [ ]:
arrays=[[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]]
for array in arrays:
  ter=False
  if sum(array)==0:
    ter=True
  print(array, '\tTerminal:', ter)

[0, 2, 1, 0, 0] 	Terminal: False
[0, 0, 0, 3, 4] 	Terminal: False
[0, 0, 0, 0, 0] 	Terminal: True
[0, 0, 0, 0, 0] 	Terminal: True
[0, 0, 0, 0, 0] 	Terminal: True


[
  
`  [0,1,0,0,0,1] `,  # s0, the initial state, goes to s1 and s5 with equal probability

 ` [4,0,0,3,2,0] `,  # s1 can become s0, s3, or s4, but with different 
  probabilities
  
 ` [0,0,0,0,0,0]`,  # s2 is terminal, and unreachable (never observed in practice)

 ` [0,0,0,0,0,0]`,  # s3 is terminal

 ` [0,0,0,0,0,0]`,  # s4 is terminal

 ` [0,0,0,0,0,0]`,  # s5 is terminal

]

s2 has probability 0

s3 has probability 3/14

s4 has probability 1/7

s5 has probability 9/14

In [ ]:
# S5 PROBABILITY

# [s0 -> s1 -> s0] -> s5

a=4/9
b=0.5
z=b+\# b: 1, a: 0
b*a*b+\# b: 2, a:1
b*a*b*a*b+\# b:3, a:2
b*a*b*a*b*a*b+\# b:4, a:3
b*a*b*a*b*a*b*a*b+\# b:5, a:4
b*a*b*a*b*a*b*a*b*a*b+\# b:6, a:5
b*a*b*a*b*a*b*a*b*a*b*a*b+\
b*a*b*a*b*a*b*a*b*a*b*a*b*a*b+\
b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b+\
b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b+\
b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b+\
b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b

(z).as_integer_ratio()

#Fraction(z).limit_denominator()


SyntaxError: ignored

In [ ]:
b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b

In [ ]:

#(np.round(z,8)).as_integer_ratio()

Fraction(*z.as_integer_ratio()).limit_denominator()

# S5 PROBABILITY

a=4/9
b=0.5

z=b*(a*b)**0+\
b*(a*b)**1+\
b*(a*b)**2+\
b*(a*b)**3+\
b*(a*b)**4+\
b*(a*b)**5+\
b*(a*b)**6+\
b*(a*b)**7+\
b*(a*b)**8+\
b*(a*b)**9+\
b*(a*b)**10+\
b*(a*b)**11#a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b

(z).as_integer_ratio()
Fraction(*z.as_integer_ratio()).limit_denominator()




NameError: ignored

In [ ]:
# S5 PROB
a=4/9
b=0.5
z1=sum([b*(a*b)**i for i in range(12) ])
#Fraction(*z.as_integer_ratio()).limit_denominator()

# print('A: ',[b*(a*b)**0,b*(a*b)**1,b*(a*b)**2,b*(a*b)**3])
# [b*(a*b)**i for i in range(11) ]
print("S5 PROB: ", Fraction(*z1.as_integer_ratio()).limit_denominator(),'\n')


# S3, S4 PROB
a=4/9; b=2/9; c=.5

z2=sum([c*b*(a*c)**i for i in range(12) ])


def sumRepProb(A):
  return (A**(50+1)-1)/(A-1)
#S0 --> S2 --> S4
z2=(sumRepProb(c*a))*b*c
print("S4/S3 PROB: ",Fraction(*z2.as_integer_ratio()).limit_denominator())

#str(Fraction(*z2.as_integer_ratio()).limit_denominator()).split('/')[1]





S5 PROB:  9/14 

S4/S3 PROB:  1/7


In [ ]:
a=4/9; b=3/9; c=.5
A=(a*c)

-A/(A-1)


z=sum([A**i for i in range(12) ])


#A=3/5
A1=3
A2=5

z1x=(A1**(120+1)-1)/(A1-1)
z2x=(A2**(120+1)-1)/(A2-1)

zx=(A**(120+1)-1)/(A-1)


z=zx*c*b
str(Fraction(*z.as_integer_ratio()).limit_denominator()).split('/')


['3', '14']

In [ ]:
(1/2)*(3/9)+(1/2)*(4/9)*(3/9)*(1/2)+(1/2)*(4/9)*(1/2)*(4/9)*(3/9)*(1/2)+(1/2)*(4/9)*(1/2)*(4/9)*(1/2)*(3/9)*(1/2)
#3/14

# S3 and S4  PROBABILITY
a=4/9; b=2/9; c=.5
z=c*(a*c)**0*b+\
c*(a*c)**1*b+\
c*(a*c)**2*b+\
c*(a*c)**3*b+\
c*(a*c)**4*b+\
c*(a*c)**5*b+\
c*(a*c)**6*b+\
c*(a*c)**7*b+\
c*(a*c)**8*b+\
c*(a*c)**9*b+\
c*(a*c)**10*b+\
c*(a*c)**11*b+\
c*(a*c)**12*b+\
c*(a*c)**13*b+\
c*(a*c)**14*b+\
c*(a*c)**15*b
#3/14
Fraction(z).limit_denominator()

Fraction(1, 7)

In [ ]:
(1/2)*(3/9)+(1/2)*(4/9)*(3/9)*(1/2)+(1/2)*(4/9)*(1/2)*(4/9)*(3/9)*(1/2)+(1/2)*(4/9)*(1/2)*(4/9)*(1/2)*(3/9)*(1/2)
#3/14

# S3 PROBABILITY
a=4/9; b=3/9
z=0.5*b+\
0.5*a*0.5*b+\
0.5*a*0.5*a*0.5*b+\
0.5*a*0.5*a*0.5*b*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*a*0.5*a*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*a*0.5*a*0.5*a*0.5
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9+\
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9
0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9
# 0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9+\
# 0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9+\
# 0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9+\
# 0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9+\
# 0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9+\
# 0.5*a*0.5*a*0.5*b*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*a*0.5*0.5*a*a*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9
# #0.5*4/9*0.5*4/9*0.5*3/9*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*4/9*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5
#0.5*4/9*0.5*4/9*0.5*3/9*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*4/9*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5+*4/9*0.5
#0.5*4/9*0.5*4/9*0.5*3/9*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*4/9*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5+*4/9*0.5*0.5*4/9+\
#0.5*4/9*0.5*4/9*0.5*3/9*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*4/9*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5+*4/9*0.5*0.5*4/9*0.5*4/9
#0.5*4/9*0.5*4/9*0.5*3/9*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5*0.5*4/9*4/9*.5*4/9*0.5*4/9*0.5*4/9*0.5*4/9*0.5+*4/9*0.5*0.5*4/9*0.5*4/9*0.5*4/9



#3/14
Fraction(z).limit_denominator()

Constraints 

---

#### Python
======

Your code will run inside a Python 2.7.13 sandbox. All tests will be run by calling the solution() function.

Standard libraries are supported except for bz2, crypt, fcntl, mmap, pwd, pyexpat, select, signal, termios, thread, time, unicodedata, zipimport, zlib.

Input/output operations are not allowed.

Your solution must be under 32000 characters in length including new lines and and other non-printing characters.

In [ ]:
 
import numpy as np
b=[0]
c=0
d=0
z=0
n=int(1e4)
for i in range(n):
  while b[0]==0:
    z+=1
    a=np.random.choice([1, 5],1, p=[0.5, 0.5])

    if a[0]==1:
      b=np.random.choice([0,3, 4],1, p=[4/9, 3/9, 2/9])
      if b[0]==4:
        c+=1;
       
    else:
       d+=1
       break
  
  b=[0]

    
        # break;

    # else:
    #   b[0]=0
    #   break;





In [ ]:
import numpy as np
from fractions import Fraction

m=[[1,2,2,0,0,3],
[2,0,0,3,5,0],
[0,0,2,0,7,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]

#a0*a0*...*a1*b0*a1*b0...*a1*b3


mp=[m[i]/np.sum(m,axis=1)[i] for i in range(len(m))]


A=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
B=np.random.choice([0,3,4],1, p=[2/10, 3/10,5/10])
C=np.random.choice([2,4],1, p=[2/9, 7/9])

def sumRepProb(A):
  return (A**(50+1)-1)/(A-1)
#S0 --> S2 --> S4

z=sumRepProb(mp[0][0])*sumRepProb(mp[1][0]*mp[0][1])*mp[0][2]*sumRepProb(mp[2][2])*mp[2][4]
z=sumRepProb(mp[0][0])*sumRepProb(mp[1][0]*mp[0][1])*mp[0][1]*mp[1][3]

Fraction(*z.as_integer_ratio()).limit_denominator()








/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]


Fraction(12, 133)

### The matrix for the below example:

` m=[[1,2,2,0,0,3], `

` [2,0,0,3,5,0], `

` [0,0,2,0,7,0], `

` [0,0,0,0,0,0], `

` [0,0,0,0,0,0]] `

In [ ]:
import numpy as np
n=int(1e4)
a=[0]; b=[0]
c=0
for i in range(n):
  a=[0]; b=[0]
  while a[0]==0:
    a=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
  if a[0]==1:
    while b[0]==0 and a[0]==1:
      b=np.random.choice([0,3,4],1, p=[2/10, 3/10,5/10])
      a=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
      while a[0]==0:
        a=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
    if b[0]==3:
      c+=1

  
  

c/n
# def arand():
#   a=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
#   while a[0]==0:
#     a=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
#   if a[0]==1:
#       return True
# def brand():
#   #b=[0]
  
#   b=np.random.choice([0,3,4],1, p=[2/10, 3/10,5/10])
#   while b[0]==0:
#     if arand():
#       b=np.random.choice([0,3,4],1, p=[2/10, 3/10,5/10])
    
#   if b[0]==3:
#       return True

# n=int(1e3)
# c=0
# for i in range(n):
#   #a=[0]; b=[0]
  
#   # while a[0]==0:
#   #   a=np.random.choice([0,1,2, 5],1, p=[1/8, 2/8,2/8,3/8])
#   if arand():
#     # while b[0]==0:
#     #   b=np.random.choice([0,3,4],1, p=[2/10, 3/10,5/10])


#     if brand():
#       c+=1

# c/n


0.0926

In [ ]:
# #[i for i in m [e for e in i]]
# n=m
# print([t for t in [n[i:(i+4)]  for i in range(4)]])


mprob=[m[i]/np.sum(m,axis=1)[i] for i in range(len(m))]



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


In [ ]:
from fractions import Fraction
# Fraction(c/n)[0]/Fraction(c/n)[1]
Fraction(np.round(c/n,4)).limit_denominator()

Fraction(463, 5000)

In [ ]:

m=[[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,0,3,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]


m=np.array([[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,1,0,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])
dm2=dict()
for t in term:
  #print(t,':\t',np.count_nonzero(np.nonzero(m)[1] == t))
 # dm[t]=np.count_nonzero(np.nonzero(m)[1] == t)
  for rowi in range(len(m)):
    if m[rowi][t] >0:
      dm2.setdefault(t, []).append(rowi)
      #dm2[t].append(rowi)

#np.nonzero(m)[0].reshape(np.array(term).shape)



#print(dm2)
M=[]
for k in dm2.keys():
  if len(dm2[k])>1:
    for v in dm2[k]:
      mx=deepcopy(m)
      #print(mx[v][k])
      mx[v][k]=0

      M.append(mx)
if len(M)<2:
  M=[m]
M

[array([[2, 1, 3, 0, 0, 1],
        [4, 0, 0, 3, 0, 0],
        [0, 1, 3, 1, 0, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]), array([[2, 1, 3, 0, 0, 1],
        [4, 0, 0, 3, 2, 0],
        [0, 1, 3, 1, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])]

In [ ]:
dm2

{4: [1], 5: [0]}

In [ ]:
# 1. Index the terminals of any given square matrix
# 2. Find 'root paths'
    # Which arrays contain the terminal state?
# 3. Add generalized conditions
# 4. Treat double (or alternative) cases/paths
# 5. Treat 'cyclic' paths
from copy import deepcopy

m=[[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,0,3,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]


m=np.array([[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,1,0,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])
m=np.array(m)
# Index terminals:
term=np.where(np.sum(m, axis=1)==0)[0]
# P=0 terminals:
p0term=np.where(np.sum(m, axis=0)==0)[0]

#list(term).remove(p0term)
   


nonterm=np.setdiff1d(list(range(len(m))),term)


# Remove P=0 terminals from term list

indp0=np.where(term==p0term)
term=np.delete(term,indp0)    

term
nonterm

def hasInd(m,nonterm, state):
  for i in nonterm:
    if state in np.nonzero(m[i])[0]:
      return i
  return -1



# Prepare matrices


lstx2=[]
for m in M:

  #print(m)
  for t in term:
    #for v in dm2[t]:
      lstx=[]
      while t>0:
        lstx.append(t)
        t=hasInd(deepcopy(m),nonterm,t)
        if t==0:
          lstx.append(t)
          break
      lstx2.append(lstx)

  
lstx2
#term
#dm2
#M
lstx3=np.unique(lstx2)

lstx3



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:43: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


array([list([4]), list([4, 1, 0]), list([5, 0])], dtype=object)

In [ ]:
lstx3[0]

In [ ]:

m=[[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,0,3,1,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]

In [ ]:
# term
# for row in m:
#   print(row)
m=np.array(m)
np.zeros(m.shape, dtype='bool')

print(m)
np.where(m)

print(lstx2)
updmat=[]
for row in m:
  if row[4] !=0:
    row[4]=0
  updmat.append(row)
np.array(updmat)

[[2 1 3 0 0 1]
 [4 0 0 3 2 0]
 [0 1 3 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[4, 3, 1, 0], [5, 0], [4, 1, 0], [5, 0]]


array([[2, 1, 3, 0, 0, 1],
       [4, 0, 0, 3, 0, 0],
       [0, 1, 3, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [277]:
# find how many times a term state is represented
# in nonterm part of the matrix

m=[[0,1,0,0,1,1],
[4,0,0,3,2,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]


m=np.array([[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,4,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])



m=np.array([[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])

[np.count_nonzero(m == t) for t in term]
dm=dict()
dm2=dict()
for t in term:
  #print(t,':\t',np.count_nonzero(np.nonzero(m)[1] == t))
 # dm[t]=np.count_nonzero(np.nonzero(m)[1] == t)
  for rowi in range(len(m)):
    if m[rowi][t] >0:
      dm2.setdefault(t, []).append(rowi)
      #dm2[t].append(rowi)

#np.nonzero(m)[0].reshape(np.array(term).shape)



print(dm2)
M=[]
for k in dm2.keys():
  if len(dm2[k])>1:
    for v in dm2[k]:
      mx=deepcopy(m)
      print(mx[v][k])
      mx[v][k]=0

      M.append(mx)
M

{4: [1], 5: [0]}


[]

In [5]:
m

array([[0, 1, 0, 1, 0, 1],
       [4, 0, 0, 3, 0, 0],
       [3, 1, 3, 1, 0, 0],
       [4, 1, 1, 5, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# Basic root paths:
lstx2
#nonterm

#np.array(m).remove



[]

In [ ]:
lstx=[]
a=4
a=hasInd(m,nonterm,a)
lstx.append(a)
a=hasInd(m,nonterm,a)
lstx.append(a)

lstx


[1, 0]

In [ ]:
lstx3
#M

array([list([4, 1, 0]), list([5, 0])], dtype=object)

In [ ]:
import numpy as np
mm=[[1,1,1],[1,1,-1],[1,-1,-1]]

np.linalg.inv(mm)


In [ ]:

m=[[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,0,3,1,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]

m

# Find cyclic patterns:
# [0,[1,0,1,0,1,0]]; 
np.array([list([3, 1, 0]), list([4, 1, 0]), list([4, 2, 0]), list([5, 0])], dtype=object)

#s0-->s1-->[s1-->s3-->s1...-->s3-->[s5-->s3-->s5-->s3...--->s5]]-->s4

lstx3[0][::-1]

#s0--s1-->s3

m=[[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,0,3,1,0,0],
[0,4,0,0,0,0],
[0,0,0,0,0,0],
[3,0,0,0,0,0]]

# print(m[0][1])
# print(m[1][0])

# print(m[1][1])
# check:

# print(m[1][2])
# print(m[2][1])
# print(m[2][3])
# print(m[3][2])

# print(m[3][4])
# print(m[4][3])

# print(m[1][3])
# print(m[3][1])
# print(m[1][4])
# print(m[4][1])


lstx3
term


m=np.array([[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,4,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])





m=np.array([[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,1,0,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])

# 0,1 0,2 0,3 ...


# 1,0
# 1,2 [2,1] 1,3 [3,1] 1,4 [4,1]

# 2,1 [2,3] 3,2 [2,4] 4,2

# 3,2 [3,4] 4,3 

# 4,3  


# 2,0


sets=[]
cycles=[]
for i in range(m.shape[0]):
  for j in range(m.shape[1]):

#   print(i)
   #if i != j:
   if set((i,j)) not in sets:
      sets.append(set((i,j))) 

      if m[i][j] != 0 and m[j][i] != 0:
        print('CYCLE:')
        cycles.append((i,j))

      
      print("m[{}][{}] = {}".format(i,j,m[i][j]))
      print("m[{}][{}] = {}".format(j,i,m[j][i]),'\n')






CYCLE:
m[0][0] = 2
m[0][0] = 2 

CYCLE:
m[0][1] = 1
m[1][0] = 4 

m[0][2] = 3
m[2][0] = 0 

m[0][3] = 0
m[3][0] = 0 

m[0][4] = 0
m[4][0] = 0 

m[0][5] = 1
m[5][0] = 0 

m[1][1] = 0
m[1][1] = 0 

m[1][2] = 0
m[2][1] = 1 

CYCLE:
m[1][3] = 3
m[3][1] = 1 

m[1][4] = 2
m[4][1] = 0 

m[1][5] = 0
m[5][1] = 0 

CYCLE:
m[2][2] = 3
m[2][2] = 3 

m[2][3] = 1
m[3][2] = 0 

m[2][4] = 0
m[4][2] = 0 

m[2][5] = 0
m[5][2] = 0 

m[3][3] = 0
m[3][3] = 0 

m[3][4] = 1
m[4][3] = 0 

m[3][5] = 0
m[5][3] = 0 

m[4][4] = 0
m[4][4] = 0 

m[4][5] = 0
m[5][4] = 0 

m[5][5] = 0
m[5][5] = 0 





```
[
[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,1,0,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]
]
```



In [ ]:
sets
cycles
lstx3

array([list([4, 1, 0]), list([4, 3, 1, 0]), list([5, 0])], dtype=object)

In [ ]:
cycles

[(0, 0), (0, 1), (1, 3), (2, 2)]

In [ ]:
set((0,1))==set((1,0))
term

array([4, 5])

In [8]:
m

array([[0, 1, 0, 1, 0, 1],
       [4, 0, 0, 3, 0, 0],
       [3, 1, 3, 1, 0, 0],
       [4, 1, 1, 5, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [36]:
# 1. Index the terminals of any given square matrix
# 2. Find 'root paths'
    # Which arrays contain the terminal state?
# 3. Add generalized conditions
# 4. Treat double (or alternative) cases/paths
# 5. Treat 'cyclic' paths
from copy import deepcopy
import numpy as np

m=np.array([
[2,1,3,3,0,1],
[4,2,4,3,2,0],
[3,1,3,1,1,0],
[4,1,1,5,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])


m=[
[0,1,0,1,0,1],
[4,0,0,3,2,0],
[3,1,3,1,1,0],
[4,1,1,5,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]]
m=[[0,1,0,0,0,1],
   [4,0,0,3,2,0],
   [0,0,0,0,0,0],
   [0,0,0,0,0,0],
   [0,0,0,0,0,0],
   [0,0,0,0,0,0]]




m0=deepcopy(m)

m=np.array(m)

diag=deepcopy(m).diagonal()
np.fill_diagonal(m, 0)

# Index terminals:
term=np.where(np.sum(m, axis=1)==0)[0]
# P=0 terminals:
p0term=np.where(np.sum(m, axis=0)==0)[0]



nonterm=np.setdiff1d(list(range(len(m))),term)


# Remove P=0 terminals from term list
indp0=np.where(term==p0term)
term=np.delete(term,indp0)    


# prepare dict
dm2=dict()
for t in term:
  #print(t,':\t',np.count_nonzero(np.nonzero(m)[1] == t))
 # dm[t]=np.count_nonzero(np.nonzero(m)[1] == t)
  for rowi in range(len(m)):
    if m[rowi][t] >0:
      dm2.setdefault(t, []).append(rowi)
      #dm2[t].append(rowi)




dtrm=dict()
for trm in term:
  trmd=np.nonzero(m[:,trm])[0]
  if len(trmd)>1:
    
    dtrm[trm]=deepcopy(m)[:,trm]
    m[:,trm]=0

M=[]
if len(dtrm)>0:
  for k in dtrm.keys():
    for i in range(len(dtrm[k])):
      if dtrm[k][i]>0:
        mc=deepcopy(m)

        #print("mcki:",mc[k,i])

        val=deepcopy(dtrm[k][i])
        mc[:,k][i]=val

        M.append(mc)



for k in dm2.keys():
  if len(dm2[k])>1:
    for v in dm2[k]:
      mx=deepcopy(m)
      #print(mx[v][k])
      mx[v][k]=0

      M.append(mx)
if len(M)<2:
  M=[m]

# M=[MM[2]]
# M=[m]
# M=[m]
#np.nonzero(m)[0].reshape(np.array(term).shape)



def hasInd(m_,nonterm, state):
  for i in nonterm:
    
    if state in np.nonzero(m_[i])[0]:
      

      return i
  return -1



lstx2=[]
for m_ in M:

  #print(m)
  for t in term:
    #for v in dm2[t]:
      lstx=[]
      while t>0:
        lstx.append(t)
        t=hasInd(m_,nonterm,t)
        if t==0:
          lstx.append(t)
          break
      lstx2.append(lstx)


lstx2
#term
#dm2
#M
roots=np.unique(lstx2)
rootss=deepcopy(roots)
roots=[]
for root in rootss:
  if 0 in root:
    roots.append(root)

# lstx3


#print(dm2)





sets=[]
cycles=[]
for i in range(m.shape[0]):
  for j in range(m.shape[1]):

#   print(i)
   #if i != j:
   if set((i,j)) not in sets:
      sets.append(set((i,j))) 

      if m[i][j] != 0 and m[j][i] != 0:# and i!=j:
#        print('CYCLE:')
        cycles.append((i,j))

      
      # print("m[{}][{}] = {}".format(i,j,m[i][j]))
      # print("m[{}][{}] = {}".format(j,i,m[j][i]),'\n')


for i in range(len(diag)):
  if diag[i]>0:
    cycles.append((i,i))

np.fill_diagonal(m,diag)
print('roots: {}, cycles: {}'.format(roots, cycles))



roots: [[3, 1, 0], [4, 1, 0], [5, 0]], cycles: [(0, 1)]


In [22]:
m0

[[0, 1, 0, 1, 0, 1],
 [4, 0, 0, 3, 2, 0],
 [3, 1, 3, 1, 1, 0],
 [4, 1, 1, 5, 1, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [189]:
m=np.array([
            
[0,1,0,1,0,1],
[4,0,0,3,2,0],
[3,1,0,1,1,0],
[4,1,1,0,1,4],
[0,0,0,0,0,0],
[0,0,0,0,0,0]

])
m

array([[0, 1, 0, 1, 0, 1],
       [4, 0, 0, 3, 2, 0],
       [3, 1, 0, 1, 1, 0],
       [4, 1, 1, 0, 1, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [214]:
np.fill_diagonal(m, 0)#[0, 0, 2, 0,2 , 3])
m.diagonal()
m

array([[0, 1, 0, 1, 0, 0],
       [4, 0, 0, 3, 0, 0],
       [3, 1, 0, 1, 0, 0],
       [4, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [161]:

m=np.array([
[0,1,0,1,0,1],
[4,0,0,3,2,0],
[3,1,3,1,1,0],
[4,1,1,5,1,4],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])
print(m)
print(M)


#for trm in term:

# np.nonzero(m[:,2])[0]

dtrm=dict()
for trm in term:
  trmd=np.nonzero(m[:,trm])[0]
  if len(trmd)>1:
    print(m[:,trm])
    dtrm[trm]=deepcopy(m)[:,trm]
    m[:,trm]=0

M=[]
if len(dtrm)>0:
  for k in dtrm.keys():
    for i in range(len(dtrm[k])):
      if dtrm[k][i]>0:
        mc=deepcopy(m)

        #print("mcki:",mc[k,i])
        print("dtrm[k][i]:",dtrm[k][i])
        val=deepcopy(dtrm[k][i])
        mc[:,k][i]=val
        print("mcki:",mc[k,i])
        print("mc:",mc)
        M.append(mc)



[[0 1 0 1 0 1]
 [4 0 0 3 2 0]
 [3 1 3 1 1 0]
 [4 1 1 5 1 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[array([[0, 1, 0, 1, 0, 0],
       [4, 0, 0, 3, 0, 0],
       [3, 1, 3, 1, 1, 0],
       [4, 1, 1, 5, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])]
[0 2 1 1 0 0]
[1 0 0 4 0 0]
dtrm[k][i]: 2
mcki: 0
mc: [[0 1 0 1 0 0]
 [4 0 0 3 2 0]
 [3 1 3 1 0 0]
 [4 1 1 5 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
dtrm[k][i]: 1
mcki: 0
mc: [[0 1 0 1 0 0]
 [4 0 0 3 0 0]
 [3 1 3 1 1 0]
 [4 1 1 5 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
dtrm[k][i]: 1
mcki: 0
mc: [[0 1 0 1 0 0]
 [4 0 0 3 0 0]
 [3 1 3 1 0 0]
 [4 1 1 5 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
dtrm[k][i]: 1
mcki: 0
mc: [[0 1 0 1 0 1]
 [4 0 0 3 0 0]
 [3 1 3 1 0 0]
 [4 1 1 5 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
dtrm[k][i]: 4
mcki: 0
mc: [[0 1 0 1 0 0]
 [4 0 0 3 0 0]
 [3 1 3 1 0 0]
 [4 1 1 5 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [170]:
# M[2][3,4]=1
MM[1]
#MM=deepcopy(M)
#mc[0,1]=3


array([[0, 1, 0, 1, 0, 0],
       [4, 0, 0, 3, 0, 0],
       [3, 1, 3, 1, 1, 0],
       [4, 1, 1, 5, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [112]:
mc[4,2]=1
mc[4,2]

1

In [58]:
2 in np.nonzero(m[0])[0]

False

In [198]:
Mprob=[]

for m in M:
  Mprob.append([m[i]/np.sum(m,axis=1)[i] for i in nonterm])
Mprob

mprob=[m[i]/np.sum(m,axis=1)[i] for i in nonterm]
Mprob

[[array([0. , 0.5, 0. , 0.5, 0. , 0. ]),
  array([0.44444444, 0.        , 0.        , 0.33333333, 0.22222222,
         0.        ]),
  array([0.6, 0.2, 0. , 0.2, 0. , 0. ]),
  array([0.66666667, 0.16666667, 0.16666667, 0.        , 0.        ,
         0.        ])],
 [array([0. , 0.5, 0. , 0.5, 0. , 0. ]),
  array([0.57142857, 0.        , 0.        , 0.42857143, 0.        ,
         0.        ]),
  array([0.5       , 0.16666667, 0.        , 0.16666667, 0.16666667,
         0.        ]),
  array([0.66666667, 0.16666667, 0.16666667, 0.        , 0.        ,
         0.        ])],
 [array([0. , 0.5, 0. , 0.5, 0. , 0. ]),
  array([0.57142857, 0.        , 0.        , 0.42857143, 0.        ,
         0.        ]),
  array([0.6, 0.2, 0. , 0.2, 0. , 0. ]),
  array([0.57142857, 0.14285714, 0.14285714, 0.        , 0.14285714,
         0.        ])],
 [array([0.        , 0.33333333, 0.        , 0.33333333, 0.        ,
         0.33333333]),
  array([0.57142857, 0.        , 0.        , 0.42857143,

In [11]:
roots

[[4, 1, 0], [4, 2, 3, 0], [4, 3, 0], [5, 0]]

In [10]:
m

array([[0, 1, 0, 1, 0, 1],
       [4, 0, 0, 3, 0, 0],
       [3, 1, 3, 1, 0, 0],
       [4, 1, 1, 5, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [37]:
# m=np.array([
            
# [0,1,0,1,0,1],
# [4,0,0,3,2,0],
# [3,1,0,1,1,0],
# [4,1,1,0,1,4],
# [0,0,0,0,0,0],
# [0,0,0,0,0,0]

# ])
m=m0
mprob=[m[i]/np.sum(m,axis=1)[i] for i in nonterm]

# Get root probs

roots[0]

probs=[]
for root in roots:
  prob=[]
  print("Path: ")
  for i in range(len(root)-1):
    print("[{},{}] ".format(root[i+1],root[i]) )
    prob.append(mprob[root[i+1]][root[i]])
    print(mprob[root[i+1]][root[i]])
  print()
  probs.append(prob)


Path: 
[1,3] 
0.3333333333333333
[0,1] 
0.5

Path: 
[1,4] 
0.2222222222222222
[0,1] 
0.5

Path: 
[0,5] 
0.5



In [38]:
print("probs: ",probs)
print("roots: ",roots)
print("cycles: ",cycles)


#sumRepProb(mprob[0][0]*mprob[0][1])



probs:  [[0.3333333333333333, 0.5], [0.2222222222222222, 0.5], [0.5]]
roots:  [[3, 1, 0], [4, 1, 0], [5, 0]]
cycles:  [(0, 1)]


In [38]:
cs=[]
q=[]
for r in roots[2]:
  if r in nonterm and r!=0:
    for c in cycles:
      if r in c and 0 not in c:
        cs.append(c)
        if r==c[0] and c[1]!=0:
          q.append(c[1])
        elif c[0]!=0:
          q.append(c[0])

if 0 in q:
  q.remove(0)


In [39]:
cs

[]

In [32]:
qpl=[]
while len(q)>0:
  qp=q.pop()
  
  for c in cycles:
    if qp in c and 0 not in c:
      cs.append(c)
      if qp==c[0] and c[1]!=0 and c[1] not in qpl:
        q.append(c[1])
      elif c[0]!=0 and c[0] not in qpl:
        q.append(c[0])
      qpl.append(qp)


In [34]:
set(cs)

{(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)}

In [10]:
set(cs )

# qp
# for c in cycles:
#   if qp in c:
#     print(c)


{(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)}

In [26]:
def getCyclePath1(root, nonterm, cycles):
  cs=[]
  q=[]
  for r in root:
    if r in nonterm and r!=0:
      for c in cycles:
        if r in c and 0 not in c:
          cs.append(c)
          if r==c[0] and c[1]!=0:
            q.append(c[1])
          elif c[0]!=0:
            q.append(c[0])

  if 0 in q:
    q.remove(0)
  return q,cs


In [27]:
def getCyclePath2(q,cs,cycles):
  
  qpl=[]
  while len(q)>0:
    # print('lenq:',len(q))
    qp=q.pop()
    # print('qp:',qp)
    for c in cycles:
      
      if qp in c and 0 not in c:
        cs.append(c)
        if qp==c[0] and c[1]!=0 and c[1] not in qpl:
          q.append(c[1])
        elif c[0]!=0 and c[0] not in qpl:
          q.append(c[0])
        qpl.append(qp)
  return set(cs)

In [43]:
cycles



[(0, 1)]

In [42]:
roots

[[3, 1, 0], [4, 1, 0], [5, 0]]

In [44]:
getCyclePath1(roots[0], nonterm, cycles)

([], [])

In [47]:
gcp1=getCyclePath1(roots[2], nonterm, cycles)
# print(gcp1)
# print(deepcopy(gcp1[0]))
getCyclePath2(gcp1[0],gcp1[1],cycles)



set()

In [233]:
cycles

[(0, 1), (0, 3), (1, 3), (2, 3), (1, 1), (2, 2), (3, 3)]

In [ ]:
cs=[]
for r in roots[0]:
  for c in set(cycles):
    if r in c and c not in cs and 0 not in c and r not in term:
      cs.append(c)
    

#list(cs)
cs
#tuple(sum(cs, [])) 
a=0

# while sdiff(cs, roots)!=-1:
  
#   cs.append(np.unique([e for l in cs for e in l]),roots)

roots
c0=[]
cyc=deepcopy(cycles)
for c in cycles:
  if 0 in c:
    c0.append(c)
    cyc.remove(c)
np.setdiff1d(cycles,c0)
cycles

set(c0).intersection(set(cycles))


cyc

[(1, 2), (1, 3), (2, 3)]

In [ ]:
cycles
# 0,1 -- > 1,2 --> 1,3 -- > 2,3




[(1, 2), (1, 3), (2, 3)]

In [ ]:
cyc


[(1, 2), (1, 3), (2, 3)]

In [ ]:
def sdiff(cs,roots):
  a=np.setdiff1d(np.unique([e for l in cs for e in l]),roots[0])
  if len(a)>0:
    return a
  return -1

In [ ]:
# # # Get cycle chains
# for cycle in cycles:
#   print (cycle)

# for i in nonterm:
#   for cycle in cycles:
#     if 

def checkcyc(cycles,n):
  
  # for c in cycles:
  #   print(c)
    if n in cycles:
      return c
      

    return -1

print()


cyc=deepcopy(cycles)

cyc=[(0,0),(0,1),(1,1),(1,4),(4,5),(2,2),(2,4)]
# ff=[]
# f=0
# for i in nonterm:
#   while f != -1:
#     f=checktup(i,cyc)
#     ff.append(f)








# for c in cyc:
#   if c != (0,0):
#     l.append(c)
#     break



# l=[]
# for i in nonterm:




#   for c in cyc:

#     if i in c:
#       l.append(c)
#       if l and l[-1][1] in c:
#         if l[-1] != c:
#           l.append(c)

# l

# z=0
# l2=[]
# for i in nonterm:
#   l=[]
#   print(i)
#   while n!=-1:
#     if i>0:
#       z=checkcyc(cycles,i)
#       print(z)
#       l.append(z)
#   l2.append(l)

    



# def hasInd(m,nonterm, state):
#   for i in nonterm:
    
#     if state in np.nonzero(m[i])[0]:
#       return i
#   return -1


# for c in cycles:
#   print (c)

# # for i in nonterm:
# #   if i in 
# cycles








# def cycc(cyc,n):
#   for c in cyc:
#     if n in c:
#       return c
#   return -1
# n=1
# cycc(cycles[n:],n)

# for i in nonterm:
#   #print(cycles[i:])
#   for c in cycles[i:]:
#     cyc=deepcopy(cycles)
    
#     if cyc.pop()[1] in c:
#       print(c)
  
cycles


# for c in cycles:

#   print(c)
# cyc=deepcopy(cycles)
# l=[]
# for i in range(len(cyc)-1):
#   if cyc[i][1]==cyc[i+1][0]:
# #     l.append(cyc[i+1])

# while cyc:
#   cx=[cyc.pop()]
#   for c in cyc:
#     if cx[-1][0] in c or cx[-1][1] in c:
#       cx.append(c)
#       print('c:',c)
for c in cyc:
  if  in c:
    cyc.remove(c)
cyc

[(0, 0), (1, 1), (4, 5), (2, 2), (2, 4)]

In [ ]:
cyc

[(0, 1), (1, 1), (1, 4), (4, 5), (2, 2), (2, 4)]

In [ ]:
def matchtup(cycles,a,b):
  for c in cycles:
    
    if a in c or b in c and (c != (a,b) and c!= (b,a) and c!=(0,0)):
      return c
  return -1

t=cycles[2]
t=matchtup(cycles[1:], t[0],t[1])

t

(0, 1)

In [ ]:
print(m)
print(dm2)
print("M: ",M)
print(term)



mprob

m[0]
np.sum(m,axis=1)[3]
[m[i]/np.sum(m,axis=1)[i] for i in nonterm]

[[2 1 3 0 0 1]
 [4 0 0 3 2 0]
 [0 1 3 1 0 0]
 [0 1 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
{4: [1, 3], 5: [0]}
M:  [array([[2, 1, 3, 0, 0, 1],
       [4, 0, 0, 3, 0, 0],
       [0, 1, 3, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]]), array([[2, 1, 3, 0, 0, 1],
       [4, 0, 0, 3, 2, 0],
       [0, 1, 3, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])]
[4 5]


[array([0.28571429, 0.14285714, 0.42857143, 0.        , 0.        ,
        0.14285714]),
 array([0.44444444, 0.        , 0.        , 0.33333333, 0.22222222,
        0.        ]),
 array([0. , 0.2, 0.6, 0.2, 0. , 0. ]),
 array([0. , 0.5, 0. , 0. , 0.5, 0. ])]

In [ ]:
m=np.array([
[2,1,3,0,0,1],
[4,0,0,3,2,0],
[0,1,3,1,0,0],
[0,1,0,0,1,0],
[0,0,0,0,0,0],
[0,0,0,0,0,0]])
# prepare dict
dm2=dict()
for t in term:
  #print(t,':\t',np.count_nonzero(np.nonzero(m)[1] == t))
 # dm[t]=np.count_nonzero(np.nonzero(m)[1] == t)
  for rowi in range(len(m)):
    if m[rowi][t] >0:
      dm2.setdefault(t, []).append(rowi)
      #dm2[t].append(rowi)
M=[]
for k in dm2.keys():
  if len(dm2[k])>1:
    for v in dm2[k]:
      mx=deepcopy(m)
      #print(mx[v][k])
      mx[v][k]=0

      M.append(mx)
if len(M)<2:
  M=[m]
M
m
# m=np.array([
# [2,1,3,0,0,1],
# [4,0,0,3,2,0],
# [0,1,3,1,0,0],
# [0,1,0,0,1,0],
# [0,0,0,0,0,0],
# [0,0,0,0,0,0]])
m

array([[2, 1, 3, 0, 0, 1],
       [4, 0, 0, 3, 2, 0],
       [0, 1, 3, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [48]:
from fractions import gcd
gcd(1/7,2/14)
def lcm(a, b):
    return abs(a*b) // math.gcd(a, b)

c:\users\roy\anaconda3\envs\tensorflow_2.x.2\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  


In [ ]:
import math
# lcm(7,14)


# 3/14; 1/7; 9/14
# l=[14,7,14]
# for n in range(len(l)-1):
#   print(lcm(l[n-1],l[n]))
c=np.unique(np.lcm.reduce(l))
for i in l:
  print(int(c[0]/i))

1
2
1


In [ ]:
l=[]
l.append(1)

In [ ]:
l.append(2)

In [ ]:
l

[1, 2]

2