In [91]:
import numpy as np

In [8]:
#n=int(6)
np.zeros(17*19).reshape(17,19)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [40]:
mmat=np.zeros(400*21).reshape(400,21)

In [44]:
mmat[:210,0]=1

In [19]:
mmat

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
mmat[:,0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [36]:
#mmat[n,j]
mmat[n,j-1]+mmat[j,n-j]

0.0

In [65]:
mmat=np.zeros(400*21).reshape(400,21)
mmat[:210,0]=1
mmat[0,0]=0
mmat

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [155]:
mmat=np.zeros(400*21).reshape(400,21)
mmat[0,0]=0
mmat[:210,0]=1
mmat[0,0]=0
for j in range(1,20):
  for n in range(1,210):
    mmat[n-1,j]=mmat[n-1,j-1]+mmat[n-j-2,j]#mmat[j-1,n]+mmat[j,n-j]

In [143]:
mmat[:10,:10]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 1.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 1.,  3.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 1.,  3.,  5.,  6.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 1.,  4.,  7.,  9., 10., 11., 11., 11., 11., 11.],
       [ 1.,  4.,  8., 11., 13., 14., 15., 15., 15., 15.],
       [ 1.,  5., 10., 15., 18., 20., 21., 22., 22., 22.]])

In [99]:
mmat.shape
t

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [202]:
mmat=np.zeros(400*21).reshape(400,21)
mmat[0,0]=0
mmat[:210,0]=1
mmat[0,0]=0
for j in range(1,20):
  for n in range(1,210):
    mmat[n-1,j]=mmat[n-1,j-1]+mmat[n-j-2,j]#mmat[j-1,n]+mmat[j,n-j]
from copy import deepcopy
a=0
s=2
for k in range(1,21):
  #print(mmat[:,k])
  t=deepcopy(mmat[:,k])
  #print(t)
  print(s)
  mmat[:,k]=0
  a+=1
  try:

    s=list(mmat[:,k-1]).index(1)+a
    mmat[s:,k]=t[:-s]
  except:


    pass

  #mmat[s:,k]=t[:-s]
  # a+=1
  # s+=a
mmat[:10,:10]

2
2
5
9
14
20
27
35
44
54
65
77
90
104
119
135
152
170
189
209


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 2., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 3., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 3., 2., 0., 0., 0., 0., 0., 0., 0.],
       [1., 4., 3., 0., 0., 0., 0., 0., 0., 0.]])

In [186]:
list(t).index(1)

1

In [122]:
mmat[k:,k]=t[:-(k+)]

In [193]:
mmat[k:,k]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [128]:
np.sum(mmat[9,])

31.0

In [175]:
list(mmat[:,1]).index(1)

1

In [213]:
X=210;Y=21
mmat=np.zeros(X*Y).reshape(X,Y)
mmat[0,0]=0
mmat[:,0]=1
mmat[0,0]=0
for j in range(1,Y):
  for n in range(1,X):
    mmat[n-1,j]=mmat[n-1,j-1]+mmat[n-j-2,j]#mmat[j-1,n]+mmat[j,n-j]
from copy import deepcopy
a=0
s=2
for k in range(1,21):
  #print(mmat[:,k])
  t=deepcopy(mmat[:,k])
  #print(t)
  print(s)
  mmat[:,k]=0
  a+=1
  try:

    s=list(mmat[:,k-1]).index(1)+a
    mmat[s:,k]=t[:-s]
  except:


    pass

  #mmat[s:,k]=t[:-s]
  # a+=1
  # s+=a
mmat[:10,:10]

2
2
5
9
14
20
27
35
44
54
65
77
90
104
119
135
152
170
189
209


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 2., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 3., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 3., 2., 0., 0., 0., 0., 0., 0., 0.],
       [1., 4., 3., 0., 0., 0., 0., 0., 0., 0.]])

In [215]:
for N in range(201):
  print(int(np.sum(mmat[N])-1))

-1
0
0
1
1
2
3
4
5
7
9
11
14
17
21
26
31
37
45
53
63
75
88
103
121
141
164
191
221
255
295
339
389
447
511
584
667
759
863
981
1112
1259
1425
1609
1815
2047
2303
2589
2909
3263
3657
4096
4581
5119
5717
6377
7107
7916
8807
9791
10879
12075
13393
14847
16443
18199
20131
22249
24575
27129
29926
32991
36351
40025
44045
48445
53249
58498
64233
70487
77311
84755
92863
101697
111321
121791
133183
145577
159045
173681
189585
206847
225584
245919
267967
291873
317787
345855
376255
409173
444792
483329
525015
570077
618783
671417
728259
789639
855905
927405
1004543
1087743
1177437
1274117
1378303
1490527
1611387
1741520
1881577
2032289
2194431
2368799
2556283
2757825
2974399
3207085
3457026
3725409
4013543
4322815
4654669
5010687
5392549
5802007
6240973
6711479
7215643
7755775
8334325
8953855
9617149
10327155
11086967
11899933
12769601
13699698
14694243
15757501
16893951
18108417
19406015
20792119
22272511
23853317
25540981
27342420
29264959
31316313
33504745
35839007
38328319
40982539
43812109
